### ISSUE TITLE
CSS comments within a SCSS file

### ISSUE THREAD

**Issue by Tregonia** [chazchumley/ohana#32]
https://github.com/chazchumley/ohana/blob/47b42fc9a83c28a77b54870fffa5f9291b85248f/src/patterns/01-core/props/_layout.scss#L3

There is a CSS comment `/**` within the include. Anywhere that this file is included, this comment will print in the CSS file.

When I see a CSS comment in a SCSS file, I think to myself .. "Does this comment have the highest level of importance, is it mission-critical, and 100% absolutely must be included in the CSS output".

Quite often, I find that the comment is actually only relevant in the SCSS source code, and is not mission critical to be output. Often these comments should be SCSS comments `//`

**Comment by chazchumley** [comment]
Replaced CSS comment with Scss comments.  Thanks Tim
